[package]
name = "cps-build"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Common Package Specification (CPS) Rust Library"
repository = "https://github.com/tylerjw/cps-build"

[dependencies]
